name: bounregistration
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk:
      flutter
  flutter_web_plugins:
    sdk: flutter
  data_table_2: ^2.2.1

  # Local Storage
  shared_preferences: ^2.0.13

  # State Management
  provider: ^6.0.2

  # Network
  dio: ^4.0.4

  # Models
  crypto: ^3.0.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Automatons
  build_runner: ^2.1.7

  # Clean code
  flutter_lints: ^1.0.4

  # Local Storage
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
